# Generated by Django 4.2.1 on 2023-05-10 11:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Up to 255 symbols', max_length=255)),
                ('category', models.CharField(choices=[('Tank', 'TK'), ('Healer', 'HL'), ('Damage dealer', 'DD'), ('Trader', 'TR'), ('Guild master', 'GM'), ('Quest giver', 'QG'), ('Warsmith', 'WS'), ('Tanner', 'TN'), ('Potion maker', 'PM'), ('Spell master', 'SM')], default=None, max_length=15)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertise',
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies_to_adv', to='AdsBoard.adv')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
    ]
