# Generated by Django 4.2.1 on 2023-05-14 12:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
