# Generated by Django 4.2.1 on 2023-05-17 09:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0002_alter_adv_content_alter_reply_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
